// <auto-generated />
using System;
using InvenireServer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvenireServer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InvenireServerContext))]
    [Migration("20250923154132_Fifth_Migration")]
    partial class Fifth_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvenireServer.Domain.Entities.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("InvenireServer.Domain.Entities.Organizations.OrganizationInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("employee_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("employee_id");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("InvenireServer.Domain.Entities.Properties.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("InvenireServer.Domain.Entities.Properties.PropertyItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateOfPurchase")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_purchase");

                    b.Property<DateTime?>("DateOfSale")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_sale");

                    b.Property<string>("Description")
                        .HasMaxLength(555)
                        .HasColumnType("character varying(555)")
                        .HasColumnName("description");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)")
                        .HasColumnName("document_number");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)")
                        .HasColumnName("inventory_number");

                    b.Property<DateTimeOffset?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)")
                        .HasColumnName("name");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)")
                        .HasColumnName("registration_number");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)")
                        .HasColumnName("serial_number");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("InvenireServer.Domain.Entities.Properties.PropertyScan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(555)
                        .HasColumnType("character varying(555)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)")
                        .HasColumnName("name");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("Scans");
                });

            modelBuilder.Entity("InvenireServer.Domain.Entities.Properties.PropertySuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(555)
                        .HasColumnType("character varying(555)")
                        .HasColumnName("description");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("Feedback")
                        .HasMaxLength(555)
                        .HasColumnType("character varying(555)")
                        .HasColumnName("feedback");

                    b.Property<DateTimeOffset?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)")
                        .HasColumnName("name");

                    b.Property<string>("PayloadString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_string");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("InvenireServer.Domain.Entities.Users.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)")
                        .HasColumnName("email_address");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("last_name");

                    b.Property<DateTimeOffset?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("InvenireServer.Domain.Entities.Users.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(155)
                        .HasColumnType("character varying(155)")
                        .HasColumnName("email_address");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("last_name");

                    b.Property<DateTimeOffset?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PropertyScanPropertyItem", b =>
                {
                    b.Property<Guid>("PropertyCheckId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PropertyItemId")
                        .HasColumnType("uuid");

                    b.HasKey("PropertyCheckId", "PropertyItemId");

                    b.HasIndex("PropertyItemId");

                    b.ToTable("PropertyScanPropertyItem");
                });

            modelBuilder.Entity("InvenireServer.Domain.Entities.Organizations.OrganizationInvitation", b =>
                {
                    b.HasOne("InvenireServer.Domain.Entities.Organizations.Organization", null)
                        .WithMany("Invitations")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InvenireServer.Domain.Entities.Users.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("employee_id");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("InvenireServer.Domain.Entities.Properties.Property", b =>
                {
                    b.HasOne("InvenireServer.Domain.Entities.Organizations.Organization", null)
                        .WithOne("Property")
                        .HasForeignKey("InvenireServer.Domain.Entities.Properties.Property", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InvenireServer.Domain.Entities.Properties.PropertyItem", b =>
                {
                    b.HasOne("InvenireServer.Domain.Entities.Users.Employee", null)
                        .WithMany("AssignedItems")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InvenireServer.Domain.Entities.Properties.Property", null)
                        .WithMany("Items")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("InvenireServer.Domain.Entities.Properties.PropertyItemLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("PropertyItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AdditionalNote")
                                .HasColumnType("text")
                                .HasColumnName("additional_note");

                            b1.Property<string>("Building")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("building");

                            b1.Property<string>("Room")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("room");

                            b1.HasKey("PropertyItemId");

                            b1.ToTable("Items");

                            b1.WithOwner()
                                .HasForeignKey("PropertyItemId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("InvenireServer.Domain.Entities.Properties.PropertyScan", b =>
                {
                    b.HasOne("InvenireServer.Domain.Entities.Properties.Property", null)
                        .WithMany("Scans")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InvenireServer.Domain.Entities.Properties.PropertySuggestion", b =>
                {
                    b.HasOne("InvenireServer.Domain.Entities.Users.Employee", null)
                        .WithMany("Suggestions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InvenireServer.Domain.Entities.Properties.Property", null)
                        .WithMany("Suggestions")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InvenireServer.Domain.Entities.Users.Admin", b =>
                {
                    b.HasOne("InvenireServer.Domain.Entities.Organizations.Organization", null)
                        .WithOne("Admin")
                        .HasForeignKey("InvenireServer.Domain.Entities.Users.Admin", "OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("InvenireServer.Domain.Entities.Users.Employee", b =>
                {
                    b.HasOne("InvenireServer.Domain.Entities.Organizations.Organization", null)
                        .WithMany("Employees")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("PropertyScanPropertyItem", b =>
                {
                    b.HasOne("InvenireServer.Domain.Entities.Properties.PropertyScan", null)
                        .WithMany()
                        .HasForeignKey("PropertyCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvenireServer.Domain.Entities.Properties.PropertyItem", null)
                        .WithMany()
                        .HasForeignKey("PropertyItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InvenireServer.Domain.Entities.Organizations.Organization", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Employees");

                    b.Navigation("Invitations");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("InvenireServer.Domain.Entities.Properties.Property", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Scans");

                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("InvenireServer.Domain.Entities.Users.Employee", b =>
                {
                    b.Navigation("AssignedItems");

                    b.Navigation("Suggestions");
                });
#pragma warning restore 612, 618
        }
    }
}
