using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using InvenireServer.Application.Attributes;
using InvenireServer.Domain.Entities;

namespace InvenireServer.Application.Dtos.Employees;

/// <summary>
/// Represents the data required to register a new employee.
/// </summary>
public record RegisterEmployeeDto
{
    /// <summary>
    /// Optional identifier for the employee. Typically generated by the system.
    /// </summary>
    [JsonPropertyName("id")]
    public Guid? Id { get; init; }

    /// <summary>
    /// Full name of the employee.
    /// </summary>
    [Required, JsonPropertyName("name"), MaxLength(Employee.MAX_NAME_LENGTH)]
    public required string Name { get; init; }

    /// <summary>
    /// Email address used to contact and log in the employee.
    /// </summary>
    [Required, JsonPropertyName("email_address"), MaxLength(Employee.MAX_EMAIL_ADDRESS_LENGTH), EmailAddress]
    public required string EmailAddress { get; init; }

    /// <summary>
    /// Password for the employee's account.
    /// </summary>
    [Required, JsonPropertyName("password"), MinLength(Employee.MIN_PASSWORD_LENGTH), MaxLength(Employee.MAX_PASSWORD_LENGTH), RegularExpression(@"^(?=.*[A-Z])(?=.*\d).+$")]
    public required string Password { get; init; }

    /// <summary>
    /// Confirmation of the password.
    /// </summary>
    [Required, JsonPropertyName("password_confirm"), SameAs(nameof(Password))]
    public required string PasswordConfirm { get; init; }
}
